language: php

php:
  - 7.1
  - 7.2

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction

script:
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)
