language: php

php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction

script:
  - composer test-cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
